// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNSkx4CA-2iU5NLXDhobtplp3KMjfpYU4',
    appId: '1:852308279412:web:3d01c66988005e753dd121',
    messagingSenderId: '852308279412',
    projectId: 'cookitnow-app',
    authDomain: 'cookitnow-app.firebaseapp.com',
    storageBucket: 'cookitnow-app.firebasestorage.app',
    measurementId: 'G-VJ4NV75V5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoi7B1vl49Xz9TQoOpceKnEqhpWVa9Jxs',
    appId: '1:852308279412:android:176caa867063312b3dd121',
    messagingSenderId: '852308279412',
    projectId: 'cookitnow-app',
    storageBucket: 'cookitnow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrO89KbmDDbOdl9KR87ZCV-_KaVc00YLA',
    appId: '1:852308279412:ios:8ef27f571b21047f3dd121',
    messagingSenderId: '852308279412',
    projectId: 'cookitnow-app',
    storageBucket: 'cookitnow-app.firebasestorage.app',
    iosBundleId: 'com.cookitnow.cookItNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrO89KbmDDbOdl9KR87ZCV-_KaVc00YLA',
    appId: '1:852308279412:ios:8ef27f571b21047f3dd121',
    messagingSenderId: '852308279412',
    projectId: 'cookitnow-app',
    storageBucket: 'cookitnow-app.firebasestorage.app',
    iosBundleId: 'com.cookitnow.cookItNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNSkx4CA-2iU5NLXDhobtplp3KMjfpYU4',
    appId: '1:852308279412:web:d2175c241187c2f63dd121',
    messagingSenderId: '852308279412',
    projectId: 'cookitnow-app',
    authDomain: 'cookitnow-app.firebaseapp.com',
    storageBucket: 'cookitnow-app.firebasestorage.app',
    measurementId: 'G-3EYC80WT9G',
  );
}
